apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workers.fullname" . }}
  labels:
    {{- include "workers.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "workers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "workers.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: workers
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
                optional: true
            - secretRef:
                name: {{ .Release.Name }}-secrets
                optional: true
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
